name: Workflow for Codecov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.11'
    steps:
    - uses: actions/checkout@main
    - name: Setup Python
      uses: actions/setup-python@main
      with:
        python-version: 3.11
    - name: Generate coverage report
      run: |
        pip install pytest
        pip install pytest-cov
        pytest --cov-report=xml
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3