name: Fastapi Doc Http Response workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test Fastapi Doc Http Response
    steps:
    - uses: actions/checkout@main
    - uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Run tests and collect coverage
      run: pytest --cov=fastapi_doc_http_response tests/ --cov-report=xml
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3